name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    name: build debug apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup java dev environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: setup gradlew permission
        run: chmod +x gradlew

      - name: build debug apk
        run: ./gradlew assembleDebug

      - name: verify debug build
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "Debug APK successfully generated."
          else
            echo "Debug APK not found!"
            exit 1
          fi

      - name: upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
          overwrite: true
